### ISSUE TITLE
Suggestions for reducing the number of sample requests

### ISSUE THREAD

**Issue by MouriNaruto** [lukasf/FFmpegInterop#14]
I've read the performance report, and if you use Media Foundation directly, you should have up to 5% more performance. (Reduce one copy per requesting.)

So, I think I should find another idea to improve this fork.

When I modify the UncompressedAudioSampleProvider class in my repo, I found if I modify it slightly the audio play will stuck.
So I debug the the AVPacket queue, and I found there wil be maximum more than 3000 AVPackets in the queue if I play my test 4k 120fps 8bit video.

So, I have an idea. 

How about decoding all AVPackets in the queue and make it in one MediaStreamSample.
It may reduce the request time.

Also I read the Microsoft's FFmpegInterop, and I found it will do the similar thing in the audio queue. (But they're just trying to gather up the minimum sampling time.)

So, I think you can try it in the audio queue. Also I am thinking that use it in the video queue, will be feasible?

Mouri

**Comment by lukasf** [comment]
I do not think it would be a good idea to do that. MF will request samples when it needs them. We should not flood the audio renderer by arbitrarily decoding and passing huge amounts of decoded samples. This would increase RAM usage and not give any benefits. Encoded data in the packet buffer is much smaller than decoded raw data in the audio renderer buffer.

The large packet buffers are most probably a result of your CPU not being able to decode in real time. So audio and video streams diverge. If they diverge, one of them reads packets far ahead of the other. So the slower stream's packet buffer will be filled up a lot, because it cannot keep up with the decode speed of the other stream. I'd guess that it is not the audio but the video packet buffer that gets so large, but that is only a guess. During normal (real time) playback, buffers should not be filled so much. But even if they are, it only increases RAM usage, but it does not add CPU overhead. So having smaller buffers would not improve the playback speed.

Audio decoding is generally very fast, and with latest multi threaded audio decoding, the delay to get the next audio sample should often be close to zero (because usually the next packet is already decoded). At least during normal playback. If the PC is not able to decode the file and all CPUs are blocked, then there can be very small delays. But then it is not a problem of audio decoding, but a problem of too slow CPU (or unneccessary resources spent elsewhere). Decoding and passing small samples instead of big samples should even reduce the delay, not increase it.

There are other technical reasons why the original FFmpegInterop is forced to concatenate packets, and since they already have to do it, they just concatenate a little more (without giving an indication of why they do it). But concatenation of samples means unneccessary copy operations, which will increase CPU usage. So it would be contrary to what you want to achieve. In this fork, audio samples are passed with zero copy, which is the most efficient decoding way.

I am not sure why you are trying so hard to get that one file running. There are no real 4K 120fps files out there, like, no movies or whatsoever. If there was a general performance problem with this lib, across all or most files, I agree we'd need to investigate. We had such problems, but all of them are fixed now, as far as I can see. I have only a few files where PotPlayer is actually a bit faster, and that is probably due to them using a custom renderer, which is somehow more effective for a few formats. If you can upload the file somewhere, I can check if it uses a special format. But since we cannot influence rendering anyways, this is there is probably not much we can do. It coud also be their ffmpeg version, but I do not believe that the performance is suddenly so much better with latest build. I plan to update to the next major ffmpeg version (3.5) when it comes out, but it is not finished yet.

**Comment by MouriNaruto** [comment]
[Video.zip](https://github.com/lukasf/FFmpegInterop/files/1747956/Video.zip)
This is the torrent of my test video. (I use the 8bit version because it can play at 120fps. My PC can't play 10bit version at 120fps.)

I also test a normal 1080p video on my major single core Yonah Celeron CPU laptop and found it unable to play it well. (Windows 10 + FFmpegInterop)
(I will buy a new 8th generation 45w i7 laptop to replace that. Because it is too weak.)

Finally, I will test the latest version of MPC-HC about that 4k video and report the result.

Mouri

**Comment by MouriNaruto** [comment]
I use the latest version of MPC-HC to play it and found it can play well. (If I disable the hardware decoding.)
MPC-HC uses 95% of CPU and 50% of GPU, same as the PotPlayer.

Mouri

**Comment by MouriNaruto** [comment]
But the FFmpegInterop uses 95% of CPU and 80% of GPU, and can't play at 120fps.

So, why UWP can't?

**Comment by lukasf** [comment]
As I said, those players use custom video presenter. It might be that they have a more efficient way to render certain (not all) video formats.

All the trackers from the torrent are down. I will leave it running for a while, but it does not look like I will receive any data.
