### ISSUE TITLE
Rotate and mirror video

### ISSUE THREAD

**Issue by grais** [lukasf/FFmpegInterop#16]
Hi, is it possible to rotate and mirror the video?
I probe the Config.FFmpegOptions.Add("vf", "transpose=1,transpose=2"); but don't work.
I use RTMP live stream..

**Comment by lukasf** [comment]
Hi, we have just added support for audio effects, but video effects are not implemented yet. A problem with specifically video rotation is that the output image can have a different resolution and aspect ration than the input image. We will only find out once the first image is rendered, but we need to tell the MediaFoundation engine the output resolution before playback starts.

This makes adding video filters a bit more complicated. I am not yet sure how to approach that problem. Either you'd need to tell us the output resolution together with the filter definition, or we'd need to decode the first image, check resolution and then initialize MF with the formats (and keep the decoded image stored for when playback actually starts). The latter would be the more flexible approach, but also the most complicated.

Video rotation could also be achieved by using MF attributes, but there is no such attribute for video mirror/flip, so it won't help for your case. It would be more perormant because it is applied by MF during rendering on the GPU.

**Comment by mcosmin222** [comment]
I don't think MF_MT_VIDEO_ROTATION attribute alters the resolution of the samples. MF simply figures it out by itself. But I am not sure how that would react with switching it mid playback.

**Comment by lukasf** [comment]
Sure, the MF attributes would not cause problems. But if we add ffmpeg video effects, nothing prevents people from adding rotate, crop, scale, whatever video effects, which will cause different output resolution. 

If @grais wants mirror/flip, then that can only be done with ffmpeg effects, and then we have to think about how such situations can be handled. It is not as simple as audio effects, where we can just resample to the desired sample rate/format if we get unexpected output from the filter.

**Comment by mcosmin222** [comment]
If someone were to use implement a video filter, they'd have to do it in a way that they can plug the filter into the framework and just work. That includes rescaling, interoplation, clipping, padding and other related activities.

**Comment by grais** [comment]
Hi. I just want rotate and play, because somtime the streaming phone make a wrong orientation. So i want set the orientation only one time before start playing. and no more time. (or i will stop recreate and start again the playing options..)

**Comment by mcosmin222** [comment]
You can play with MF_MT_VIDEO_ROTATION attribute, we use it to correct orientation for rotated videos.

**Comment by lukasf** [comment]
Yes, if you only need rotation, things get a lot easier.

**Comment by grais** [comment]
Yes! Thanks for all. That's working!

**Comment by lukasf** [comment]
@grais: If you want to bring your solution back into the repo, feel free to open a PR or create a new issue to discuss it. I will be closing this one for now...
