### ISSUE TITLE
ffmpeginterop vs Vlc for winrt?

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#25]
Since you guyx have good experience in ffmpeg stuff, I was wondering whether you are aware of the vlc build for win rt? which is also open source? Probably you do know abt that 
**vlc-winrt** by official vlc team it is code for the vlc uwp app on the store. 
https://code.videolan.org/videolan/vlc-winrt

**Vlc Media Element** it is sort of a custom Control made to immitate **MediaElement** control of the uwp element using the **libvlc** as playing source of the files.
https://github.com/kakone/VLC.MediaElement

**libvlc-uwp** is the port of libvlc library ( open source vlc library ) for uwp
https://github.com/ZhaoYunxiong/libVLCX.UWP

So the reason I wanted to provide you guyx with all these sources about vlc stuff on uwp is because I wanted to have a discussion about **ffmpeginterop on uwp** vs **vlc on uwp**  so that we can discuss pros and cons of each. and maybe improve this fork with some features from vlc as well?

So far what I know abt these 2 is that with ffmpeginterop we can use **MediaPlayerElement** and hence more features of the platform control of uwp. But with **VLC.MediaElement** we r limited to the features which were immitated by the creator of that repo. but if we see the code of **vlc-winrt-uwp** the app which is already on store from vlc team, it seems to do a lot of features, including all kinds of subs and audio stream switching as well. I am not sure about which is more performant or efficient though :)

So let the discusiion begin :) @lukasf  @mcosmin222

**Comment by mcosmin222** [comment]
The biggest problem with VLC and any of its code components is the license. If you use it, you have to make all your app open source, which is unsuitable for a wide range of applications (basically, you can't monetize it). And reverse engineering would take too long and not yield any benefits in the long run. If we were to integrate VLC components into ffmpeginterop, ffmpeginterop would also switch to the more restrictive licensing. 

Microsoft has a good team of engineers it is just that they lack direction. VLC does have a lot of bugs, especially on mobile (it hicks up on Android, and it never really worked well for me on windows mobile). 
And besides, VLC lib is a fork of FFMPEG. 

FFMPEG interop can plug into any windows rendering component. We are not limited to MediaPlayerElement. We can use MediaElement as well, and we can also create custom rendering surfaces. But the moment we do that, we give up a lot, and since there is just a few of us doing it, mostly in our spare time, I do not see the benefits. We would basically have to keep up with Microsoft and recover at the same time. In my app I've been implementing lots of custom stuff in the past because Windows's equivalents were bad or didn't offer nearly the same features, but this changed in windows 10 with the rapid feature releases.

**Comment by touseefbsb** [comment]
good point about the liscence, I didnt know tht so thanks for the info. so yeah we haveto keep focused and keep improving the ffmpeginterop for uwp.
