### ISSUE TITLE
update readme with sample app features

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#29]
there are some booleans on the left pane which obviously have some effect on the video, which I dont know about. as you can see in the picture. 
![image](https://user-images.githubusercontent.com/11542189/37511027-1d27fb38-291f-11e8-90c0-5842c789d95f.png)

so it would be great if we can know the details of them hence we can decide when and how we should use them in our apps , or should all of them just be pushed to true?

**Comment by touseefbsb** [comment]
I understand what exact seek for exact frame does, it extracts frame exactly at the spot of the playing video, and if off then a random frame is picked right? But I dont understand what other toggles are doing, all of those passthrough toggles and allow Iyuv Video Output?

**Comment by lukasf** [comment]
For the frame grabber, you always have to specify a position. The sample uses the playback position, but in code you can specify any position. If you set Exact Seek to false, then the frame grabber will grab the next key frame before that position. This will be very fast, but it is usually not exactly the position you gave it. If you set it to false, it will decode from the key frame until it reaches the exact position you specified. This means it has to decode mutliple frames until it reaches the exact position. This can be quite a lot slower, depending on the file and codec. For most use cases (including seek preview), it will be better to set this to "false".

All other options should be left at default. Passthrough means that the lib does not decode this format with ffmpeg and passes the encoded packets to the MF engine instead. This allows MF to do hardware decoding if possible, which is a lot faster if available. It makes sense to add settings in your app to disable passthrough for specific formats, since some PCs might have problems with hardware decoding.

Passthrough for audio usually does not make sense, except if you run on a phone which might have a HW decoder for MP3 or AAC.

**Comment by touseefbsb** [comment]
@lukasf  so what does passthrough actually means? it means tht for that format it will try to use hardware acceleration? yes these options can be provided in the app, but a normal user of a media app will not know wht to do with these settings, so I think as developer we need to know wht should be the best for most use case scenarios? so we can set them accordingly in code behind. so the default values as in the sample app are best for most use cases right? and in code behind we can check if device is phone then we can passthrough the audio decoders as well.

**Comment by touseefbsb** [comment]
I mean user may understand mp4, mkv extensions but they usually don't know wht H264 etc means

**Comment by lukasf** [comment]
The defaults are set to what makes sense for most users. It depends a bit on your target audience if you want to expose ways to change this. There are also technically advanced users who want to fine-tune app settings, and they will sure know what H264 or HEVC means. Look at popular players such as MPC-HC and others, they are full of advanced options. But if you add this, you should probably put it in some "expert settings" area or whatever. Users should only touch them if they know what they are doing.

**Comment by touseefbsb** [comment]
perfect thanks for clarification @lukasf

**Comment by mcosmin222** [comment]
BTW, the sample is just for developer purposes, so there is no point in being overly user friendly, these properties match the ffmpeg config object.
