### ISSUE TITLE
AVFrame to AudioFrame/VideoFrame

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#4]
If we can find a way to create an AVFrame from an AudioFrame, we can levrage this library with the IBasicAudioEffect or IBasicVideoEffect for lower letancy when applying effects

https://docs.microsoft.com/en-us/uwp/api/windows.media.audioframe

I had some attempts at doing this, but I always failed at filling the AVFrame with the buffer reference obtained from an AudioFrame.

Can someone with little less bias take a look at this?

I tried the example shown here

https://ffmpeg.org/doxygen/2.7/libavcodec_2utils_8c_source.html#l00478
But it looks like the AudioFrame coming from MF has too little samples
Thanks.

**Comment by lukasf** [comment]
I am not sure what you mean with "has too little samples". Do you have your source code on github? I could maybe take a look.

MF always uses packed audio (non-planar), so you must select e.g. AV_SAMPLE_FMT_S16 instead of e.g. AV_SAMPLE_FMT_S16P. The packed format only uses one buffer per sample, whereas planar would have one buffer per channel. But I don't know if that is your problem without seeing the code.
