### ISSUE TITLE
volume 200 support

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#49]
vlc players and libraries usually support volume upto 200 I was wondering whether that can be done in this library as well? or is that out of score for this library?

**Comment by lukasf** [comment]
This should be possible by using audio effects. Check SetAudioEffects function and refer to ffmpeg filter documentation to see which effects are available and which options must be set. I'd recommend to only set an effect when you increase volume beyond 100%, to avoid unneccessary processing of audio data. So for 0-100% use normal volume from MediaElement, for > 100% add audio effect, when back to <= 100%, remove effect.

https://www.ffmpeg.org/ffmpeg-filters.html#volume

**Comment by touseefbsb** [comment]
@lukasf  thanks I will try it

**Comment by mcosmin222** [comment]
You should know that having extra volume through a filter is not the same as having extra volume from the hardware. The filter will not be as accurate, whereas hardware increased volume will always sound better.

Be sure to make that obvious on your UI.

**Comment by lukasf** [comment]
Going beyond 100% can also introduce severe distortions if the source audio is already close to 100%. Be sure to check out parameters of the filter, to reduce clipping artifacts.

VLC has the >100% area colored orange-red to indicate that this is critical volume level.

**Comment by mcosmin222** [comment]
Other players offer a more fine grained control over the volume filter, and provide a "bar" with db scale just like an equalizer.

**Comment by touseefbsb** [comment]
thanks for tip guys ,  @mcosmin222  when you say filters are different from hardware volume, can you explain that? I mean all hardwares usually have only 100 percent volume right? vlc apps usually break that barrier and push the volume upto 200 which is why that quality of volume above 100 is usually bad, vlc also uses filters? or do they do hardware volume upto 200?

**Comment by mcosmin222** [comment]
We deal with sampled audio at software level, not continuous audio. As such, we can only increase the volume _mathematically_, through the use of filters. Because we have a sampled signal, we may introduce artifacts like @lukasf mentioned.
VLC is also using filters. Only the OS API can control the hardware volume.

Hardware amplification usually has better quality because it no longer deals with sampled audio, so the chances of generating artifacts is almost null (considering it is good quality hardware). You may still get artifacts or uneven sound at high volumes, but that depends entirely on the quality of the hardware.

The topic deals with pretty advanced mathematics, I just gave you the outlook.

**Comment by touseefbsb** [comment]
ahan got it. so I should also go with the filters

**Comment by mcosmin222** [comment]
You have no other choice.
