### ISSUE TITLE
How M3U8 decode works

### ISSUE THREAD

**Issue by ramtinak** [lukasf/FFmpegInterop#51]
Hi, I just find out m3u8 is a plain text file that's include stream files.
My question is how FFmpeg can render a text file and convert it to video output?
Am I right about this:
for example this is a M3u8 file (note: for online tv):
```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:1893
#EXT-X-PROGRAM-DATE-TIME:2018-05-24T13:09:08.227+00:00
#EXTINF:10.000,
PMC_1527655574251_1893.ts
#EXTINF:10.000,
PMC_1527655574251_1894.ts
```

FFmpeg every 11 seconds(or milliseconds|I really don't know is sec or milli sec) request for new m3u8 and gets TS file and  join these files as a 1 stream and decode it.

here is a m3u8 url:

```http://63.237.48.28/ios/PMC/PMC.m3u8```

**Comment by mcosmin222** [comment]
The m3u8 file is an extension of the plain old m3u file, which uses UTF-8 encoding rather than ASCII. The m3u family of files are playlist files.

The #EXT and #EXTINF lines are metadata about the file directly beneath it. FFMPEG cannot render a text file as a video file.

Instead, the actual streams for you to play are the ones without the #EXT prefix, so in your case, it is PMC_1527655574251_1893.ts and PMC_1527655574251_1894.ts. It is these streams you should try to open with ffmpeg. The metadata around them will simply give you more hints on how to open them (for example, it tells you the duration). 

As far as I know, FFMPEG cannot decode the m3u file directly (I may be wrong though). You will need to parse it yourself and give the streams you find to FFMPEG.

**Comment by lukasf** [comment]
I could be wrong but I do not believe that ffmpeg will do that. You probably have to do this yourself: Parse the file, extract the URIs. To get gapless playback, you could try to create a new MediaPlaybackList with the part files.

**Comment by mcosmin222** [comment]
You should also know that m3u has no standard specifications. The metadata present in #EXT lines is always custom and it is usually produced so a specific player can understand it. In my app I simply ignore the metadata and proceed to just play the streams.

**Comment by ramtinak** [comment]
Thanks for answer,
FFmpeg and even MediaElemet/Player can play m3u8 urls(online tv). I know that because I tested these urls.
My question was how its work. and I got my answer.

Thanks again.

**Comment by ramtinak** [comment]
just one more thing,
full path of an stream will be like this? 
http://63.237.48.28/ios/PMC/PMC_1527655574251_1893.ts

**Comment by mcosmin222** [comment]
Yes.
