### ISSUE TITLE
windows foundation exception

### ISSUE THREAD

**Issue by touseefbsb** [lukasf/FFmpegInterop#52]
I recently added **appcenter** to my uwp app to get more details on the crashes, and here is a new wierd crash stacktrace which is probably also linked with ffmpeginterop and also threading, it has words like dispatch and threadpool so I wonder what I did wrong in my code, is there some rules about threading in uwp or c# which maybe I am not following, hence causing so much crashes? and why cant I reproduce them?

**exception** : ?__abi_windows_foundation_?$typedeventhandler@p$aavmediastreamsource@core@media@windows@@p$aavmediastreamsourcesamplerequestedeventargs@234@___abi_idelegate____abi_invoke@?q__abi_idelegate@?$typedeventhandler@p$aavmediastreamsource@core@media()

**StackTrace**

ucrtbase.dll
_invoke_watson() invalid_parameter.cpp:224
vccorlib140_app.DLL
__abi_FailFast() vccorlib.cpp:19
vccorlib140_app.DLL
__abi_translateCurrentException() exceptions.cpp:578
FFmpegInterop.dll
?__abi_Windows_Foundation_?$TypedEventHandler@P$AAVMediaStreamSource@Core@Media@Windows@@P$AAVMediaStreamSourceSampleRequestedEventArgs@234@___abi_IDelegate____abi_Invoke@?Q__abi_IDelegate@?$TypedEventHandler@P$AAVMediaStreamSource@Core@Media() +0x0000000000000060
Windows.Media.dll
Microsoft::WRL::Details::DelegateArgTraits_long (__stdcall Windows::Foundation::ITypedEventHandler_impl_Windows::Foundation::Internal::AggregateType_Windows::Media::Core::MediaStreamSource *,Windows::Media::Core::IMediaStreamSource *_,Windows F() event.h:245
Windows.Media.dll
Microsoft::WRL::InvokeTraits_2_::InvokeDelegates__lambda_7b7e616a644a9110f730fe32bf2798b4_,Windows::Foundation::ITypedEventHandler_Windows::Media::Core ISingleSelectMediaTrackList *,IInspectable *_ _() event.h:534
Windows.Media.dll
Microsoft::WRL::EventSource_Windows::Foundation::ITypedEventHandler_Windows::Media::Playback::MediaPlaybackTimedMetadataTrackList *,Windows::Media::Playback::TimedMetadataPresentationModeChangedEventArgs *_,Microsoft::WRL InvokeModeOptions_2_ _() event.h:812
Windows.Media.dll
CWinRTMediaStreamSource OnSampleRequested() winrtmediastreamsource.cpp:738
Windows.Media.dll
CMFMediaStreamSourceEventQueue::CSampleRequestEvent ProcessEvent() mfmediastreamsource.cpp:5623
Windows.Media.dll
CMFMediaStreamSourceEventQueue DispatchOperation() mfmediastreamsource.cpp:5165
Windows.Media.dll
COpQueue ProcessMarshalledOperations() opqueue.cpp:319
Windows.Media.dll
COpQueue::ProcessMarshalledOperationsAsyncCallback Invoke() opqueue.h:136
RTWorkQ.dll
ThreadPoolWorkCallback() workqueue.cpp:1812
ntdll.dll
TppWorkpExecuteCallback() work.c:671
ntdll.dll
TppWorkerThread() worker.c:1109
kernel32.dll
BaseThreadInitThunk() thread.c:64
ntdll.dll
__RtlUserThreadStart() rtlstrt.c:997
ntdll.dll
_RtlUserThreadStart() rtlstrt.c:914

**Comment by mcosmin222** [comment]
OK, first of all, get yourself up to date with the theory. Be sure to follow the links in this order:

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/

Especially this part is fundamentally useful

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/threading/thread-synchronization

Once you get used to these problems you can start tracking down where your issue might be.

I found this thing particularity useful in my app

https://github.com/StephenCleary/AsyncEx/wiki/AsyncLock

I see your problem is related to TimedMedataTracks, which are subtitles in our case. Our code looks pretty thread safe inside the library, don't you agree @lukasf ?

I really don't see how you could possibly cause a thread race at library level. I am guessing the race happens sometime before, and the stack trace is just throwing you off course.

**Comment by touseefbsb** [comment]
yeah these thread operations usually are misleading, that is why recently I have been following functional programming, with immutable objects and pure functions, which is supposed to solve many possible problems bcz of multi-threading. I will also look at the links u provided so that I can try to solve it for now, and in the long run I may rewrite my app in functional programming

**Comment by mcosmin222** [comment]
I am closing this since it is likely not a lib problem. When it is sure that it is a lib problem, we can open another issue and I will see with @lukasf  how to fix it. If you need further guidance, post here.

Thanks.
