### ISSUE TITLE
ffmpeg reader queue grows large

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#53]
Issue forked from #42 

Hello everyone,

This is an issue I found in the following file. 

https://1drv.ms/u/s!Ao-WOwsImxSMtuUqBqB2dkK5Gp0YJA

I have around 99 MKV files which reproduce this issue, so I guess it is wide spread.

The problem: 
Usually, you would expect a media file to have stream packets like this:

A V A V A V, where A and V are packages coresponding to audio or video streams. This seems to be the case for the majority of containers. 

The problem is, in the files I found, the packages are like this:

A V A V A A A A A A A A A...A A A A V A V A A A A A V

In our current implementation, we share one ffmpeg reader between all sample providers. It reads each pocket in sequential manner, and enqueues it to the package queue of its corresponding sample provider.

In the case of the above, the ffmpeg reader will pile up a bunch of audio packages when it looks for a video package.

**What my proposed solution is:**

Separate ffmpeg readers for Audio and video streams. Each Audio stream will have its own reader. This will prevent calls to video stream samples from enqueuing packages into audio sample providers. 

Video streams will share a ffmpeg reader with subtitle sample providers, as they are linked, and there is no sample request for subtitle streams.

**Challenges:**

We can do this using IRandomAccessStream.CloneStream method. Should allow us to clone the input stream whenever we need it.

What happens when you try to open an URL stream with this same problem? I only experienced this on local file where opening a stream is possible.

**Comment by lukasf** [comment]
As I wrote in #42, I would propose to not do anything about this. This is the normal way of working for a decoder pipeline. Packet buffers usually level out after a while. Please observe playback over a longer period of time, not only beginning of playback.

**Comment by lukasf** [comment]
Ok if you get 5GB or memory usage, then there is something else going seriously wrong. This can't be caused just by the normal interleaving offset. Either packets or samples are not released properly, that's my guess.

**Comment by mcosmin222** [comment]
The trend is to steadily increase memory over time. I got to this part following the memory profile from VS. For the moment it is the best bet we have. You can reproduce it with sample app too. 

I am currently going through the whole 45 minutes to get a screenshot at the end.

**Comment by touseefbsb** [comment]
you guyx are speaking in high level language which I am not totally getting, the only think which I picked from the discussion is that @mcosmin222  mentioned the problem is reproducible with sample app but not with vlc or or movies & TV app, so that means this is not one of those rare scenarios which occurs in every media player.

**Comment by mcosmin222** [comment]
@lukasf 
after 20 minutes of playback

![image](https://user-images.githubusercontent.com/9284164/41179727-5c778802-6b74-11e8-8bcc-d951d375b496.png)

You can easily guess where it will be after 40.

**Comment by lukasf** [comment]
And you are sure that the 5GB incident was not caused by the other Windows bug where samples are not released when player is minimized?

I have played a different huge MKV file (16GB high bitrate) for 10 minutes now with the sample app and saw only 10MB increase in memory, starting at 130MB, now at ~140MB. During last minutes there was not much change, very solid memory consumption, moving around 140. This is what I always see. No way how this could go up to 5GB.

If you can upload the full 2GB file somewhere, I would give it a run here as well. But I don't believe that I will see the same happening, because I never saw that happening and I played a lot of huge MKVs.

@touseefbsb I have not been able to reproduce this with the sample app. @mcosmin222 is using the latest Windows version, which already had a different bug causing huge memory consumption in media players. Right now I assume this might be a Windows bug as well.

**Comment by lukasf** [comment]
Now my file played for 20 minutes as well, task manager shows 139MB.

**Comment by mcosmin222** [comment]
@lukasf OK, I will look for a way to upload it.

**Comment by lukasf** [comment]
Are you using software or hardware decode?

**Comment by mcosmin222** [comment]
![image](https://user-images.githubusercontent.com/9284164/41179888-04e39e22-6b75-11e8-982a-bd193d434bac.png)

Got to 1.2 GB now :)

**Comment by mcosmin222** [comment]
![image](https://user-images.githubusercontent.com/9284164/41180006-6fb9352c-6b75-11e8-9437-c852893d6242.png)

**Comment by lukasf** [comment]
Oh, I used SW decoding. After switching to HW decode, I see memory growing as well!! Seems there is a leak in our passthrough implementation.

**Comment by mcosmin222** [comment]
Sample app crashed after 30 minutes of playback at 1.4 GB.

Look, I am not saying this is 100% the issue, but this is the best bet I've got.

**Comment by lukasf** [comment]
This could be pretty simple: In ComplressedSampleProvider::CreateNextSampleBuffer we take the next AVPacket - but we don't free it. That's probably not a very good idea ;)

**Comment by mcosmin222** [comment]
Are you sure we don't free it somewhere else?

**Comment by lukasf** [comment]
I think I have already solved this. Will create PR in a minute!

**Comment by mcosmin222** [comment]
Ah yes, we don't. Only in uncompressed we do :)

**Comment by mcosmin222** [comment]
I am guessing you will do

**Comment by lukasf** [comment]
Yes. PR is there #54. Please verify on your side. For me it work fine now.

**Comment by lukasf** [comment]
It is also very likely the reason for crashes @touseefbsb reported in #42

**Comment by mcosmin222** [comment]
Yes, I agree on that.

**Comment by mcosmin222** [comment]
Well I am guessing a fresh set of eyes always helps :)

**Comment by touseefbsb** [comment]
I have also applied the fix, lets hope this fixes some memory issues in my app as well :)
