### ISSUE TITLE
MediaPlaybackList adapter

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#55]
Hello,

I've been wondering, since this has come up a few times here.
Should we include an adapter for MediaPlaybackList to work with this library?

For example, the adapter would have a list of "stream sources" (uris, IRandomAccessStreams, Files etc) and would automatically create a MediaPlaybackList of 3 items (the currently played item in the middle, and previous and next items) to achieve gapless playback.

I have a rough idea on how this should work, if it is to have it implemented I will do most of the work.

What do you think @lukasf, @touseefbsb?

**Comment by touseefbsb** [comment]
I will gladly share the work I have done for this in my app, so maybe you can look at that and then look at your own implementation and then maybe bring most refined way to do it for this library which then everyone can use :) @mcosmin222

**Comment by lukasf** [comment]
Hi, generally I like the idea. But it is a difficult topic, and it's not easy to implement a solution that really works well for a lot of scenarios. And the solution should be easy to integrate with a dev's internal app structure.

Some things to consider: Opening items in ffmpeg is rather expensive. Maybe the user only wants to take a short look at a file and then close it right away. It would be bad to have opened three items in that case, because you'd only really need one. The previous item is generally not neccessary for gapless playback, only the next item. Next item does not need to be opened right away, it would be sufficient to open and add it a few seconds before the end of the current item.

We'd need some kind of synchronization between the MediaPlaybackList, the MediaPlayer and the adapter list. And we probably need events to notify the app of track changes.

What if the user wants to edit the list? When he changes the next track but we already loaded that one, then we'd need to remove the old one and load the new one. So synchronization also must work in the other direction. Changes to the adapter list must result in changes to the MediaPlaybackList (if its items are affected).

**Comment by mcosmin222** [comment]
Hello @lukasf 

I actually looked into 2 ways of doing it: 

1. somehow create a lazy loaded MediaPlaybackItem. This is not possible, because MediaPlaybackItem requires a fully initialized MediaSource to work with. And MediaSource is sealed class. 

2. Have a base interface/class/whatever, call it IFfmpegInterop, which will have a method "OpenFFmpeg" or something. Then have classes for opening FFMPEG media stream sources for each possible source: uri, stream, file, etc. 

The adapter itself will be presented as a List of IFfmpegInterop. This adapter will handle the opening and closing of media sources when needed. The adapter will also need the MediaPlayer in order to respond to its events. The user will only interact with this adapter. Now, to answer some of your questions:

1) If the user modifies the list, and the current MediaPlaybackItem is removed, then playback will stop and start from the begining (or next/previous file - we could make it configurable).

2) Good point about the previous item, we can drop it, so we are down to 2.

3) We can open the next item as soon as the first has started playback. There is no need to wait until the last moment, memory consumption shouldn't be all that high. Again, this could be configurable (give an TimeSpan offset from the end of the current track when the next one should be opened, similar to MaxPreftchTime on the MediaPlaybackList itself).

Again, this is just a sketch. The best way to do this would be to have Microsoft implement a lazily loaded MediaSource. CC @khouzam

**Comment by touseefbsb** [comment]
@mcosmin222  about the lazy loading, I am implementing it in a way, not sure if its the best way , I am creating a mediaPlaybackItem on demand, the code checks if their is already media source loaded, if not then the object creats the media source and media playbackitem from the storageFile , note that I have a custom class for this purpose so that one object can have mediaplaybackitem and storagefile together hence making the lazy initialization of mediaplaybackitem possible.

**Comment by mcosmin222** [comment]
@touseefbsb that is somewhat different topic. I'd say that should be application specific logic.

@lukasf another idea, to make it easier to inject custom logic for applications: Have a request callback to fetch the next MediaPlaybackItem. We would need a deferal implementation for this.

So, the adapter would need the following functionality

1) Start off by having 1 or more MediaPlaybackItems.
2) Maintain the MediaPlaybackList, by requesting new MediaPlaybackItems when needed
3) Forward the state events from MediaPlayer (MediaOpened, MediaFailed are particularly important)

Methods:
1) MoveNext, loads the preloaded next MediaPlayerItem, requests a new one if it doesn't have one
2) MovePrevious, requests the previous MediaPlaybackItem, and loads it
3) Recreate/reset/whatever, unloads the currently loaded MediaPlaybackItem, and starts playback from the new list.
4) Dctor

Of course, everything would have to be mutex locked. The biggest issue I see is cancellation of operations (for example, reset would have to cancel MoveNext/MovePrevious).

**Comment by lukasf** [comment]
I still cannot fully imagine how this would look like. Also some things are a lot easier to implement in app's C# code, especially all that multi threading and synchronization stuff. Still, I am not against it. If a good solution can be found, it would sure be a valueable addition to the lib.

We'd also have to consider cases where we have already loaded the next MediaPlaybackItem, but then the user changes the next item (not the current). So there must be a way to notify the adapter that the playlist has changed. Then we could fire a event to ask which is the next item, and if it is different from what we currently have, we have to discard it and request the new item to be loaded. For that we'd need two events. One to request the item (maybe with one Location enum parameter Current, Previous, Next, and one Item get/set parameter of type "Object"), then a second event to actually load the MediaPlaybackItem (has Item read-only parameter and MediaPlaybackItem get/set).

We might also need custom status handling, independend of (but connected to) MediaPlayer. Like when user calls MoveNext, our status should already be "Loading" (while we create the MediaPlaybackItem), although the MediaPlayer's status is still "Playback". This could be a bit tricky to get right. Maybe it's not a must-have, but it would definitely be nice.

**Comment by touseefbsb** [comment]
@lukasf  ofcourse in some cases it would be simpler to write the logic in the app code, so we can just provide instructions and features of this adapter in readme, and it will be optional for the developer, if they like the implementation and it suits them, they can use it otherwise they can choose not to use it and implement their own, or they can even go full custom and fork the repo to extend and change the implementation to their own liking ( if they know wht they are doing with it ) for their own projects.
also we can have a general, adapterChanged event with its arguments specifying which type of change has occured and which index, which item, etc.

**Comment by mcosmin222** [comment]
@touseefbsb of course, it will always be optional, we will not hide the other ways of consuming this library, just like we did not hide MediaStreamSource API when we introduced the MediaPlaybackItem API.

**Comment by mcosmin222** [comment]
@lukasf I think we might be able to do this job in C#, but exposing the class as a WindowsRuntimeComponent.

**Comment by lukasf** [comment]
@mcosmin222 Doing this in C# should make the implementation job a lot easier. Since we are not dealing with actual samples or data, there are no concerns regarding GC for this part. And I also think it would be a good idea to expose it as a Runtime Component, so it can still be consumed from any language.

**Comment by mcosmin222** [comment]
@lukasf So then we settled this part. C# + winRT component. I will try to come up with a sketch impl as soon as possible, and then we will have something concrete to talk about.

**Comment by mcosmin222** [comment]
Even in C# this proves to be quite tricky due to windows runtime limitations on public members.

**Comment by mcosmin222** [comment]
Ok, I uploaded the sketch

The branch https://github.com/lukasf/FFmpegInterop/tree/MediaPlaybackAdapter contains the code.

I know it is not finished, probably not even correct. This is just how I imagined it the first time around

Problems so far: 

1) The StreamBuilder has to keep the stream open. This still incurs performance overheads for opening the streams.

2) There are quite a few edge cases to getting the "next" and "previous" items when needed. I totally ignored the "get the next item a few seconds before it is needed". That's just a little too advanced for this topic so far.

this is a throwaway implementation, I just wanted to try my hand at it and see how it goes, where the edge cases are. I realized there are quite a few unanswered questions, and that we shouldn't answer them for our consumers.


The event based idea I had was to use an event (you can see the left over classes there) to signal the app to get the next item.
These 2 implementations could co-exist. The problem I saw the first time I tried it was exposing everything as AsyncOperation and never use async/await in public methods. That is also the case here. In any case, switching to an event based approach is quite trivial now and only requires the removal of some members and some more advanced thread synchronisations. Then the app will have to handle all its edge cases the way it sees fit.

While implementing this I realized I basically had to re-write all the complicated logic I already have in my app for this workflow, so I am guessing the event based system should be the way forward, because it will allow to reuse the logic and we don't have to recreate everything from scratch.

**Comment by mcosmin222** [comment]
@lukasf I uploaded the event based model. 

- I've implemented a crude deferal, although there could probably be easier approaches to avoid the wrath of an async void wait-up (for example, instead of asking for the completed MediaPlaybackItem in the request, we could request the IAsyncOperation which creates it, and then await it at the other end).
- I've added some tests to see how this performs. Surprisingly, I could not get the list to behave like I would expect it to. Apparently, if you add a new item to the list, it seems it is ignored. Looks like the list will only be aware of the items there were in it when the MediaPlayer.Source property is assigned.
- There is still a long way to go, you are right that this is very complicated.

What do you think?

**Comment by lukasf** [comment]
@mcosmin222 Sorry for late response. I am pretty busy right now, but I just looked over the event based solution. Here are some thoughts:

- Event based solution looks cleaner to me.
- Why do you implement your own deferral when you can use the one from Windows.Foundation?
- Synchronization is still something that needs to be addressed. What do you think about making the adapter a DispatcherObject? This would allow us to synchronize on the UI thread and prevent some race conditions that could occur then we use other locking strategies. But it also has some downsides and limits use to UI applications and a single view. Maybe manual locking is the better approach. Just a thought I had...
- We cannot rely on playback list's current index. It takes time to create items, it takes time to skip items. We'd need our own previous, current, next storage mechanism. And we need to make sure that an item after it was loaded is still the right item.

**Comment by mcosmin222** [comment]
@lukasf Don't worry, I am kind of busy myself nowadays, haven't had much time to do anything more:

1) I 100% agree the event based soolution is better.

2) You still need to handle the synchronisation even if you use the Windows.Foundation deferal. I could go as far as implementing IDeferal. At this point I am still not sure if we should even use the deferal. We can avoid it completely by asking the user to provide the IAsyncOperation which will create the MediaPlaybackItem, and we can await it on our side.

3) There is little to no synchronisation in there yet. Much work to be done here I agree, but I don't think it is a good idea to tie this to the UI thread. We will probably revert to manual control. Messy, but it is flexible

4) Maybe this is why my feng shui isn't working...

**Comment by lukasf** [comment]
@mcosmin222 This is more a detail and can be done later, still: I'd propose to go with UWP Deferral class. You pass a handler which will be called on completion. You can use a TaskCompletionSource which you set when this handler is invoked. Then you have a task you can wait for. Deferral is the way how this kind of stuff is done in UWP and devs are used to it. But it can be added later, it's not so important now. Synchronization is the much more important (and difficult) part...

**Comment by lukasf** [comment]
Looks good with the new provider class! It's probably easier to implement for devs. 

Regarding unit testing: Have you tried to work with interfaces instead of classes? Like using IMediaPlayer6 and IMediaSource? UWP usually makes it pretty hard to use interfaces. But I believe here it could work, because IMediaPlayer.Source is actually IMediaSource and not the implementation class. So you could theoretically write a fake IMediaPlayer to (async) raise events on file open and test against that (unless I am missing something). It's still of course neccessary to test this in a real app, and if it works there, that's fine for me, no unit tests required form my side. But sometimes unit tests are helpful during development and optimization phase of complicated interaction logic.

**Comment by mcosmin222** [comment]
I don't think it is possible. Looking at

https://github.com/tpn/winsdk-10/blob/master/Include/10.0.16299.0/winrt/windows.media.playback.idl

It seems the interfaces are bound specifically to the MediaPlayer class. You cannot implement them in other classes (already tried that). On top of that, the MediaPlayer class seems to be considering the MediaPlaybackList as a "single" source. I believe it is the MediaPlaybackList which handles the file changes and other related operations.

**Comment by mcosmin222** [comment]
Sorry i havent done anything on the matter. Didnt have time for new features lately.

I will start working on this again soon. Having studied the existing MediaPlaybackList API, I think it might already support this scenario (the MaxPrefetchTime seems to hint at this). I need to do some testing and research on the matter.

**Comment by touseefbsb** [comment]
@mcosmin222  looking forward to it :)

**Comment by mcosmin222** [comment]
One very annoying bug is that the test stops playing mid track for no apparent reason.

**Comment by touseefbsb** [comment]
maybe the keep items open number can change that?

**Comment by mcosmin222** [comment]
No. It is probably some start positioning problem.

**Comment by lukasf** [comment]
@mcosmin222 Gapless playback is what MediaPlaybackList was created for in the first place. I am pretty sure that it is possible to achieve gapless if we use it correctly (other apps do it).

If you use ffmpeg with software decoding of mp3, please be aware that FFmpegInterop theoretically already takes care of encoder padding. So the output of an mp3 file with ffmpeg should already be with paddings removed. If it works correctly, you'd probably need to set padding to zero in MediaPlaybackList. But there could as well be problems in our implementation. I never really verified if it works 100% correct. Only if you use MP3 passthrough, you need to set the paddings for MediaPlaybackList.

**Comment by mcosmin222** [comment]
My guess is that I do not calculate the Start and Duration if the cue sheet fragments correctly. Anyway, i will publish my work once I finished this test, as it will likely mean gapless works fine.

**Comment by lukasf** [comment]
How are you creating your partial files? Proper tooling must be used to allow gapless playback. Just splitting an existing mp3 file will lead to gaps.

**Comment by mcosmin222** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediasource.createfrommediabinder#Windows_Media_Core_MediaSource_CreateFromMediaBinder_Windows_Media_Core_MediaBinder_

This seens exactly what we need yet microsoft seems to hate media stream sources.

**Comment by mcosmin222** [comment]
@lukasf maybe you can help...

So the test I am running right now is having 2 MediaPlaybackItems created from the same file, at different start positions. It should technically play the whole file in one go without gaps.

The problem is, when the MediaPlaybackList switched from one item to the other there is a click. Maybe I am not calculating the start position properly.

The way I did it is take the file, lets say it is 400 seconds long. Take a break point at 200 seconds, create one playback item which starts at 0 and has 200 seconds duration, and another playback item starts at 200 and lasts until EOF. The problem is the 200 break point cause a click. I know I am likely doing something wrong, but I am not sure what.

What I tried so far: compute the length of the sample in time (it would be 1000 / sample_rate) in miliseconds, and find the closest timestamp to 200 seconds thats a multiple of that sample duration (the point was to seek to an exact sample and not mid way, which would cause overlaps between the 2 playback item). It didn't work, the click was still there.

I also adjusted the Seek method from ffmpeginterop to do this additional check

'if (playbackItemStartTime > 0)
			{
				correctedPosition = position.Duration;
			}
			else
			{
				correctedPosition = position.Duration + (avFormatCtx->start_time * 10);
			}'

Any ideas?

**Comment by touseefbsb** [comment]
guys this might be an obvious question but this adapter would be generic and will work will all audio and video files, and not limited to audio right? asked this because I noticed a lot of "mp3" files in the discussion here.

**Comment by mcosmin222** [comment]
Mp3 files are good for testing gaplessness. Ofc it will be generic.

**Comment by mcosmin222** [comment]
A cue sheet is a type of playlist which separates multiple tracks from one file. It is a classical example of gapless playback,hence why i try to implement one with this new adapter.

**Comment by mcosmin222** [comment]
ANyway, pushed new version I have.

**Comment by lukasf** [comment]
I think the problem is more with the files you have. You cannot just split an mp3 file with an average tools and expect it to play gapless. As far as I know, for gapless playback, the files must be encoded in a way that the last samples of file A are repeated in file B. This is because first few samples of file B will be cut away as encoder padding. If file B begins at the exact point where A ends, then you would lose the first few real samples of file B. So splitting an mp3 file for real gapless playback would usually require a re-encode of the whole file. Most mp3 splitters don't do that - and you would lose quality. There are a few tools out there which try to do without re-encode by repeating larger chunks and then writing huge encoder padding in header. Pcutmp3 was one of them, but is dead now and has bugs, google tells me that mp3splt claims to support gapless in latest release.

I never tried to create gapless files by splitting. The best way is to use proper tooling when ripping the original files from CD.

**Comment by lukasf** [comment]
Oh ok... And then you are creating the playlist items manually, parsing the cue file?

I think we do not seek 100% precise at the moment. ffmpeg will seek to the closest point before that position (packet start) and then we just start delivering samples from that point. It might be that we'd need to skip samples until we reach the exact position in the audio stream. Much like we skip samples in the frame grabber implementation (when exact seek is on).

**Comment by lukasf** [comment]
I am not sure if that will do it, at least when cue points are not in sync with mp3 frame size. You might even have to seek into a frame (skip some of the data in it). It's all pretty complicated.

If you ask me, I'd rather focus on "normal" gapless playback first, which means you have multiple mp3 files from a mix album, properly encoded, and try to play them gapless.

Gapless playback of cue sheets would of course be nice as well, it's just a whole tad more complicated. You could also try to internally align cue points to mp3 frame size, which is 1152 samples. This would make things easier (and probably no one will really notice - frame size is small enough).

**Comment by lukasf** [comment]
The other approach to cue file support would of course be to only really open the file once, and handle the "virtual" files one layer above. This would allow 100% true gapless playback without any tricks. But it will make the playlist handling more complicated.

**Comment by mcosmin222** [comment]
The virtual approach is how my app does it now.

**Comment by mcosmin222** [comment]
@lukasf yeah you are right, it is too much of a hustle to do this via the MediaPlaybacklistAdapter. I tried the ffmpeg exact seek, and our exact seek and there are still gaps, so I will let it the virtual way.

**Comment by mcosmin222** [comment]
I guess calling Pause() on the MediaPlayer and Play() again after some time does cause a gap in playback xD

**Comment by mcosmin222** [comment]
I am closing this since it is too reliant on application features/logic.

Just a headsup: if you change the mediaplayers audio device property, it will cause media playback list current item property to point to the wrong playback item.
