### ISSUE TITLE
Combined media source

### ISSUE THREAD

**Issue by Tirraon** [lukasf/FFmpegInterop#56]
Hi!
Is it possible to create MediaStreamSource from multiple Url-links or streams?
For example, I have two links to video:
https://somehost.com/myvideo_part1.mp4 with duration 0:10:30
https://somehost.com/myvideo_part2.mp4 with duration 0:5:30
And MediaElement should show to user one video with duration 0:16:00 and allow to seek.

I don't know, hot to implement it in UWP without FFmpegInterop (maybe with MediaStreamSource.SampleRequested and HttpClient ?)

Thanks.

**Comment by mcosmin222** [comment]
Hello,

There are several ways you can hack your way through this:

1) Modify the library so that it creates SampleProviders for each of the links you give it. When the first sample provider runs out of samples, you switch to the 2nd. You would need to properly initialize the media stream source with the duration, and this assumes both streams have the same encoding profile (if they don't you need to ensure transcoding). In the 2nd sample provider, you need to modify the timestamps of the samples with an offset equal to the duration of the first stream. This entire logic is not present in the library, but most of it is recycling existing methods, so it'd give it a 5 on the scale of difficulty (10 in case you need transcoding).

2) Use the library as is, and abstract this detail using UI. Open both links separatly, add the resulting MediaPlaybackItems into a MediaPlaybackList. You can make your UI in such a way that you allow seeking into the 2nd file, and when happens, you signal the MediaPlaybackList to switch to the second file.  The MediaPlaybackList should allow you to seek with minimal delay, however, I am not sure what happens when playback flows naturally from the 1st to the 2nd file (it should render gaplessly though). It'd give this a 3 on the difficulty scale, since this is all about consumting, not modifying the library. This works invariant of the file encoding profiles.

3) Have a worker thread stich the files together while the StreamSource requests data from it. You would need to implement the IRandomAccessStream interface and handle all the IO yourself. 8/10 on the diffficulty scale, asuming both files have the same encoding. If they don't, you need to transcode one of them as you go, so this goes to a 11/10 difficulty.

**Comment by lukasf** [comment]
I'd recommend to solve this using method 2 as described by @mcosmin222. Just have your own custom seek bar, and switch to the respective file and position when seeking. By using MediaPlaybackList you will have gapless playback, so users won't even notice any break between files (if the files have been split correctly).

Method 1 will fail if the files do not have the exact same sample formats for audio and video. Plus it is pretty complicated to realize. Not recommended if you ask me.

Method 3 won't even work with the vast majority of file format. Files do not just contain encoded data, they contain a header at the start of the file, then packets following, then often a second header at the end which contains position information for the packets. You cannot just binary combine them (except for very few special formats).

**Comment by Tirraon** [comment]
@mcosmin222 @lukasf 
Thank you for your advice!
I will use method 2.
