### ISSUE TITLE
Add exact seek option to ffmpeg config

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#64]
We are currently using AvSeek flag backwards to perform seek operations but in some cases the AvSeek flag any (which is slower but more precise) is needed.

This should be part of ffmpeg config. Default remains flag backwards.

I will do the implementing if you are OK with it.

**Comment by lukasf** [comment]
If you use any flag, ffmpeg will not seek to keyframe but to any frame. This means that you will get broken video (or solid gray image) after seeking, until the next key frame is decoded. I do not think that this is desirable. Only when you start decoding from a key frame, you will get valid output, which is what backwards flag does. I cannot imagine that anyone wants broken output after seek.

What we could do ist seek using backwards flag, then decode and drop frames until we are at the desired position. But it is not even needed, because media foundation will already do this for us. Sometimes you might notice that after seek it takes a short moment until playback starts. This happens when we seek to key frame and a lot of frames after that need to be decoded and dropped. So MF will already do the skip-ahead to exact position for us. Unfortunately we cannot even prevent this. At least, some time back I tried to disable it by setting the actual position in OnStarted, and it had no effect. So it is more like MF enforces exact seek, and we cannot disable it.

**Comment by mcosmin222** [comment]
I was thinking of adding this flag specifically for audio. I didn't realize MF forces us to do exact seek. That is actually quite interesting.

**Comment by lukasf** [comment]
I think for audio, ffmpeg will anyways seek to packet which contains that position, so using the any flag should not make a difference there. Key frame searching is only done for video.
