### ISSUE TITLE
How about adding extra audio passthrough support?

### ISSUE THREAD

**Issue by MouriNaruto** [lukasf/FFmpegInterop#65]
We know the FFmpegInterop supports AacAdts, Aac and Mp3 passthrough. How about adding audio passthrough support for Alac, Flac and Wma?

What do you think about that?

Mouri

**Comment by lukasf** [comment]
Hi @MouriNaruto, Aac(Adts) and Mp3 have primarily been added because some phones have hardware decoding capabilities for these codecs. Using passthrough allows to save cpu and battery on such devices. 

But since Windows Phone is dead, PC is the only relevant platform for FFmpegInterop now. PCs do not have audio hardware decoders, so adding passthrough for any audio codec does not make sense. And even if you want to target Windows Phone, I am pretty sure that there are no hardware decoders for flac or alac. About wma I am not 100% sure, there might be phones who hw decode it, I don't know...

**Comment by mcosmin222** [comment]
PCs do have audio hardware decoders. There are DSP chips on motherboards, and you can buy dedicated audio cards for high performance scenarios. Regardless, none of these are really relevant to us. And even if the PC does have one of these high performance cards, we won't be able to use it anyway, unless we ship the driver along our library.

As for phones, I never saw significant differences between hardware and software decoding when it comes to battery life. The only scenario in which I see passthroughs as a must have on phones are games, where every CPU cycle matters. PC games already use their own software decoding, mostly based on FFMPEG too.

**Comment by lukasf** [comment]
Are you sure about that? Do you have more information on this? There are audio DSPs on mainboards, but as far as I know this is more about mixing, A/D D/A conversion, sometimes resampling and audio enhancements. That's all stuff that works on the already decoded output signal. I have also not heard about APIs in Windows for hardware accelerated audio decoding. So even if a high end sound card has hardware decoding DSPs, I am not sure if Windows would make use of that, except if explicitly implemented in dedicated software. On a PC it just does not make sense to hardware accelerate such a simple task. I could be wrong of course...

**Comment by mcosmin222** [comment]
I am referring specifically to compressed samples like mp3, aac and other similar stuff. These are hardware supported in some devices. the mp3 format for example is pretty trivial to decode in hardware, and all the frequency domain transformation can be offloaded to a DSP chip (almost all DSPs are capable of doing FFT, and most compressed formats revolve around FFT at some point). On top of that, windows 10 is capable of running on AMR64 CPUs, which we know support some hardware decoding, at least on the same levels as a phone. I am not sure about flac/wma though, it isn't really clear if snapdragon SOCs can do it compressed or not... 

Regardless, adding more passthroughs for audio is not going to hurt, other than taking a lot of time to baby sit all the ifs and elses. if @MouriNaruto  wants to do it, I don't see the danger. I personally fully agree with you, it is not needed, and audio filters will not work on compressed samples.

**Comment by lukasf** [comment]
I am not convinced. I did some google searches and could not find a single hint on hw accelerated audio decoding on Windows PCs, and I could not find any Windows API regarding hw acceleration for audio. The only results for this were targeting Raspberry PI and similar micro devices, but no result at all for PC. There is DirectSound Hardware Acceleration API, but as I assumed, it is only for mixing and effects, not for decoding.

I know that hw decoding mp3 is easy, sure there are DSPs for that. They are mostly used in mp3 players and smartphones. But I could not find any hint on them being used in PCs. Even if Snapdragon SOCs have such a DSP uint, I still believe that it will not be used on a Windows/ARM system, because there is no driver support in Windows for this scenario. You'd probably need special software and a custom driver to access that DSP.

Adding work and complexity in our code when there is no benefit is not a good idea. So I tend to be against adding more audio passthrough, unless someone can show me a clear advantage of adding it @MouriNaruto
