### ISSUE TITLE
Using ffmpeg to parse external subtitles

### ISSUE THREAD

**Issue by mcosmin222** [lukasf/FFmpegInterop#78]
Hello @lukasf,

Hope you are enjoying your holidays.
I got a few hours off and wanted to try out something I've been thinking for a while. You mentioned some time ago it would be cool if we could use ffmpeg to parse external subtitle files. And we can, as far as I can tell.

How I did it: downloaded some random .sub file.
use the CreateFromStreamAsync method to create the ffmpeg interop object.
Stepping through it, I followed the execution, and ffmpeg correctly detected the subtitle stream (ofc, the video and audio streams all reported junk values).

The point is, we have pretty much all the code that we need to implement this feature, and we will need a dedicated method to handle such files.

A few outstanding questions remain:

Should this method be a static of ffmpeginteropMSS class, and return the TimedMedataClass object stand alone, and let the developer decide what to do next? Practically, the same way the framegrabber works.

Should the ffmpeginteropMSS class have its own method to add an external subtitle from a given stream? This could actually be implemented using the method above...

Does this work for all subtitle formats? How many of these formats are supported? https://en.m.wikipedia.org/wiki/Category:Subtitle_file_formats

I will try to come up with a PR the following days.

**Comment by lukasf** [comment]
Hi @mcosmin222,

thanks, holdays are fine so far, hope the same for you as well!

Good to hear that ffmpeg can directly read subtitle files. I think it would be great if we could directly add subtitles to an existing interopmss instance. So if a MediaPlaybackItem was already created, the subtitle is added there. I think this should work on-the-fly, even if playback has already started. If it has not yet been created, we add the track to the internal subtitles list, so it will automatically be included once MediaPlaybackItem is created.

Some things to consider:
- Shall the whole subtitle be parsed at beginning? Embedded sub cues are added incrementally, during playback of the other streams. For external subs, we'd have to manually read packets. Either read them all upfront to fill all cues, or somehow try to sync the reading to playback of master file.
- If all cues are parsed upfront, we must do it async. Maybe the add method should be async anyways, since it already involves IO even when not reading all cues.
- Shall we consider an optional delay parameter, so we can adjust the subtitle timing? Maybe not needed in the first version, can be added later.

You said you tested with a .sub file. So is this an image based subtitle? Can it be parsed even without having the corresponding .idx file? I wouldn't even know how to give two file streams to ffmpeg...

**Comment by lukasf** [comment]
Ok, sub/idx files could be added through UWP APIs if they are not possible with ffmpeg.

**Comment by mcosmin222** [comment]
Anyway, so having looked over the code again, I think the best approach is this:

1) Leave the current ffmpeginteropMSS class mostly as is. Except it shouldn't fail if the stream only has subtitles. Subtitle infos are exposed publicly already anyway

2) Create a class, call it ExternalSubtitleProvider, which inherits from the existing subtitle provider. In addition to what it already has, it will also have a method ReadToEnd. This will read the entire stream to the end. 

3) Create helper methods to ease consumption of the above.

**Comment by mcosmin222** [comment]
NVM, i'm dumb. There's an easier way.

**Comment by mcosmin222** [comment]
Issue moved to #81.
