### ISSUE TITLE
VC1SampleProvider

### ISSUE THREAD

**Issue by sudongg** [lukasf/FFmpegInterop#86]
Is it possible to pass passthrough VC-1 , achieve VC-1 hardware decoding acceleration ?

**Comment by lukasf** [comment]
Hi @sudongg, this could be possible, but I have not tried yet.

Similar to H264 and HEVC passthrough, the stream format which the decoder expects, is not what is written in the actual file stream. Some metadata and headers need to be added. So we have to manually parse metadata, then build the packets in a format which the decoder understands. Additionally, there are two types of VC-1 out there, which need to parsed differently, so we'd need two different sample providers (similar to H264).

VC-1 Bitstream converters example:
https://codereview.chromium.org/657007

Not sure if it will work that easy, but it could be worth a try. The VC1 solution should then also work for "WMV9" (which is actually WMV3): VC-1 Simple and Main profile use WMV3 encoding, only VC-1 Advanced Profile is different.

**Comment by sudongg** [comment]
Thanks for your reply.
But I didn't find the conversion method in the example you provided. 
I tried to modify H264SampleProvider and it failed.
I may have to go to the master branch to ask for help.

**Comment by lukasf** [comment]
This one is for Simple+Main Profile:
https://codereview.chromium.org/657007/patch/2003/3014

This one is for Advanced Profile:
https://codereview.chromium.org/657007/patch/2003/3012

Of course this will need adjustments to make it work in our library. The main library Microsoft/FFmpegInterop is more or less dead right now, which is why we started this fork. Feel free to ask there, but don't expect too much.

**Comment by lukasf** [comment]
The sample I posted are just a reference of how the output stream can be built from ffmpeg input stream. This is how it is done in Chromium, and I guess it should work for us as well. When the first sample is requested (`if (!ctx->frames)`), send initial header data, after that, put the actual sample, which also needs a small header applied. All following samples only send the sample with its header. The advanced profile is a bit more complicated, since we'd need to parse out some specific values from the header...

**Comment by lukasf** [comment]
@sudongg Actually this was much easier than expected. Only after I built all that parsing into our lib, I found out that it is not even needed. So I could throw away my VC1SampleProvider and switch back to generic CompressedSampleProvider without any manual parsing. I only needed to put the extradata into codec UserData.

Please check PR #89. I also added passthrough for VP9 and MPEG2.

Note: As I said, VC-1 Simple and Main Profile is actually exactly the old WMV3 codec. So you need to enable WMV3 passthrough for VC-1 Simple and Main. Only for VC-1 Advanced Profile, the VC1 passthrough parameter needs to be enabled. But currently, both are enabled by default.

**Comment by sudongg** [comment]
Hi lukasf, after multiple sample tests, WMV3 passthrough and VC-1 passthrough are working fine, thanks.
