### ISSUE TITLE
Jump in ffmpeginterop

### ISSUE THREAD

**Issue by ramtinak** [lukasf/FFmpegInterop#9]
Hi, I want to help this project.
I know C# but this project is an C++ project.
I just have some questions about this , because I want to be useful, and can help this project.
First of all: how can you understand ffmpeg? I know there's a lot of wikis in ffmpeg sites, but those It's necessary? I really don't know how can I research about it.

Second of all: how did you do this? I really admire @lukasf because I was looking for extracting frames, he create a new branch and there's it!

3: why we cannot use ffmpeg.exe directly in our app?

A quick start will be appreciate it.

Thanks

**Comment by mcosmin222** [comment]
We cant use the exe because it is not winRT compiled.

As for the rest, it is a combination of programming experience, knowledge on the topic, ffmpeg wiki, and trial and error. Extracting frames was easy cause we already had everything in place. Other topics are more complicated.

**Comment by lukasf** [comment]
I agree that you first need some basics on C++/CX and WinRT, before jumping into the code. If you want to understand how a library works, sometimes it is useful to debug a sample and step through the code. Then you will see how the code works, how the data flow is, and you can inspect variables, etc... 

Google and ffmpeg wiki will help you if you have specific questions. You can also google for a specific ffmpeg method. Their website contains pretty good explanation of all classes and methods, and you can even directly view their sources from each method description, to see how it works internally. This is pretty well done.

I have done quite a lot of media programming in the past, and I also know C++ since quite a while, so it was not so hard for me to jump in here. Normally I am a C# developer as well, but for media stuff it is just not the right tool. It must be done in native code if you want good performance.

**Comment by lukasf** [comment]
The ffmpeg.exe can only be used to transcode files and write them out into a different file. It cannot be used for playback. And as @mcosmin222 says, it uses methods which are not allowed for a Store App, so it would not even be allowed to bring it into the Store.

**Comment by lukasf** [comment]
@ramtinak I just remembered that there is one wiki page that describes the ffmpeg decoding process pretty well:
https://www.ffmpeg.org/doxygen/3.4/group__lavc__encdec.html

It gives a pretty good idea how decoding with ffmpeg basically works. Details can usually be found in the individual api method documentation.

I will be closing this for now. Feel free to open a new issue if you have a specific question or need a feature in the lib.
